# Generated by Django 4.2.1 on 2024-05-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
    ]
