# Generated by Django 4.2.1 on 2024-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_section_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='type_of_cover',
            field=models.CharField(default='твердая', max_length=100),
        ),
    ]
