# Generated by Django 4.2.1 on 2024-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=40)),
                ('year_of_publication', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_copies', models.IntegerField()),
            ],
        ),
    ]
