# Generated by Django 4.2.1 on 2024-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='year_of_publication',
            field=models.IntegerField(null=True),
        ),
    ]
