# Generated by Django 4.2.1 on 2024-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('buyerCode', models.IntegerField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('deliveryDate', models.DateField()),
                ('formOfPayment', models.CharField(max_length=120)),
                ('typeOfDelivery', models.CharField(max_length=80)),
                ('priceOfDelivery', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
